### PR TITLE
New Mode "Circular" for buttons

### PR DESCRIPTION
**Pull request by ChrApww**
Hi, I've been setting a quite elaborate mapping for both the MiniLab 2 and the LoupeDeck (which is a brilliant controller yet a bit unfinished).
I'm designing mappings for various audio plugins from PluginAlliance amongst others, and I miss a mode along with the "incremental" mode for buttons which should be "CIRCULAR", and work like this : 
- for each impulse, increment values up to the highest value
- return to the lowest value after the highest.

That would meet many functions which have a small list of values like "pre/post/side-chain" for positioning an EQ, or  "fast/med/slow" for an attack, without the need of assigning 2 buttons to increment and decrement values...

Hope it'll find a good consensus from ReaLearn users 👍

### CODE REVIEW

**Comment by tompad2** [comment]
Isn't this already possible to do? 

Just check "Wrap" in the mapping when using Incremental button.

....and whats all this merging?

**Comment by ChrApww** [comment]
> Isn't this already possible to do?
> Just check "Wrap" in the mapping when using Incremental button.
=> thank you ! This is doing exactly what I wanted

> ....and whats all this merging?
=> idk what you're talking about...

**Comment by tompad2** [comment]
When I look at this thread I see long lists of merge messages and in the header it says "[ChrApww](https://github.com/ChrApww) **wants to merge 1,844 commits** into [feature/298-compartment-variables](https://github.com/helgoboss/realearn/tree/feature/298-compartment-variables) from [master](https://github.com/helgoboss/realearn)"

I haven't seen this in other threads I have read.....

**Comment by helgoboss** [comment]
I think because the target branch is the wrong one. It should be master instead.

@ChrApww Thanks for the PR. Can we close it? Is Wrap what you were looking for?

**Comment by ChrApww** [comment]
Hi, forgive me, I'm new to Github and haven't clearly understood how it's organized...
@helgoboss yes, the "wrap" function does what I was looking for.
By the way Benjamin, I'd like to offer some help :  how can I make a more comprehensive contact with you by mail or...?

**Comment by helgoboss** [comment]
> Hi, forgive me, I'm new to Github and haven't clearly understood how it's organized... @helgoboss yes, the "wrap" function does what I was looking for. By the way Benjamin, I'd like to offer some help : how can I make a more comprehensive contact with you by mail or...?

No problem! Thanks for the offer. By email would be the best option: info@helgoboss.org

Closing this.

**Pull request closed without merging**
